"""Programmatic Gazebo Harmonic SDF World Generator for RELLIS Outdoor Environments.

Constructs REP-compliant Gazebo Harmonic SDF worlds with authentic outdoor
surface friction zones (dirt trail, grass, mud) and natural obstacle formations.
"""

from typing import List, Optional, Tuple


class RellisWorldBuilder:
    """Builds Gazebo Harmonic SDF 1.8 / 1.9 outdoor world definitions."""

    def __init__(self, world_name: str = "rellis_outdoor_world") -> None:
        self.world_name = world_name
        self.trail_segments: List[Tuple[float, float, float, float, float]] = []  # (x, y, z, len, width)
        self.mud_patches: List[Tuple[float, float, float]] = []                    # (x, y, radius)
        self.fallen_logs: List[Tuple[float, float, float, float, float, float]] = [] # (x, y, z, roll, pitch, yaw)
        self.rock_cairns: List[Tuple[float, float, float]] = []                    # (x, y, z)

    def add_trail_segment(self, x: float, y: float, z: float, length: float = 12.0, width: float = 3.5) -> None:
        self.trail_segments.append((x, y, z, length, width))

    def add_mud_patch(self, x: float, y: float, radius: float = 1.2) -> None:
        self.mud_patches.append((x, y, radius))

    def add_fallen_log(self, x: float, y: float, z: float = 0.15, roll: float = 0.0, pitch: float = 1.57, yaw: float = 0.0) -> None:
        self.fallen_logs.append((x, y, z, roll, pitch, yaw))

    def add_rock_cairn(self, x: float, y: float, z: float = 0.20) -> None:
        self.rock_cairns.append((x, y, z))

    def generate_sdf(self) -> str:
        """Render complete Gazebo Harmonic SDF XML string."""
        sdf = f"""<?xml version="1.0" ?>
<!-- Generated by NAVIGUARD RellisWorldBuilder for Gazebo Harmonic -->
<sdf version="1.8">
  <world name="{self.world_name}">
    <physics name="1ms" type="ignored">
      <max_step_size>0.001</max_step_size>
      <real_time_factor>1.0</real_time_factor>
    </physics>

    <plugin filename="gz-sim-physics-system" name="gz::sim::systems::Physics"/>
    <plugin filename="gz-sim-user-commands-system" name="gz::sim::systems::UserCommands"/>
    <plugin filename="gz-sim-scene-broadcaster-system" name="gz::sim::systems::SceneBroadcaster"/>
    <plugin filename="gz-sim-sensors-system" name="gz::sim::systems::Sensors">
      <render_engine>ogre2</render_engine>
    </plugin>
    <plugin filename="gz-sim-imu-system" name="gz::sim::systems::Imu"/>

    <scene>
      <ambient>0.65 0.65 0.60 1.0</ambient>
      <background>0.60 0.75 0.90 1.0</background>
      <shadows>true</shadows>
      <grid>false</grid>
    </scene>

    <light type="directional" name="sun">
      <cast_shadows>true</cast_shadows>
      <pose>0 0 25 0 0 0</pose>
      <diffuse>0.95 0.92 0.85 1</diffuse>
      <specular>0.3 0.3 0.3 1</specular>
      <direction>-0.4 0.3 -0.85</direction>
    </light>

    <!-- Base Terrain -->
    <model name="rellis_base_ground">
      <static>true</static>
      <link name="terrain_link">
        <collision name="terrain_collision">
          <geometry>
            <plane><normal>0 0 1</normal><size>60 60</size></plane>
          </geometry>
          <surface>
            <friction>
              <ode><mu>0.60</mu><mu2>0.55</mu2></ode>
            </friction>
          </surface>
        </collision>
        <visual name="terrain_visual">
          <geometry>
            <plane><normal>0 0 1</normal><size>60 60</size></plane>
          </geometry>
          <material>
            <ambient>0.30 0.45 0.22 1.0</ambient>
            <diffuse>0.35 0.50 0.25 1.0</diffuse>
          </material>
        </visual>
      </link>
    </model>
"""
        # Trail segments
        for i, (tx, ty, tz, tlen, twid) in enumerate(self.trail_segments):
            sdf += f"""
    <!-- Dirt Trail Segment {i+1} -->
    <model name="trail_segment_{i+1}">
      <static>true</static>
      <pose>{tx:.2f} {ty:.2f} {tz:.3f} 0 0 0</pose>
      <link name="link">
        <collision name="col">
          <geometry><box><size>{tlen:.2f} {twid:.2f} 0.01</size></box></geometry>
          <surface><friction><ode><mu>0.85</mu><mu2>0.80</mu2></ode></friction></surface>
        </collision>
        <visual name="vis">
          <geometry><box><size>{tlen:.2f} {twid:.2f} 0.01</size></box></geometry>
          <material><ambient>0.48 0.36 0.24 1.0</ambient><diffuse>0.52 0.40 0.28 1.0</diffuse></material>
        </visual>
      </link>
    </model>
"""

        # Mud patches
        for j, (mx, my, mr) in enumerate(self.mud_patches):
            sdf += f"""
    <!-- Mud Slip Zone {j+1} -->
    <model name="mud_patch_{j+1}">
      <static>true</static>
      <pose>{mx:.2f} {my:.2f} 0.005 0 0 0</pose>
      <link name="link">
        <collision name="col">
          <geometry><cylinder><radius>{mr:.2f}</radius><length>0.01</length></cylinder></geometry>
          <surface><friction><ode><mu>0.22</mu><mu2>0.20</mu2></ode></friction></surface>
        </collision>
        <visual name="vis">
          <geometry><cylinder><radius>{mr:.2f}</radius><length>0.01</length></cylinder></geometry>
          <material><ambient>0.28 0.20 0.12 1.0</ambient><diffuse>0.32 0.22 0.14 1.0</diffuse></material>
        </visual>
      </link>
    </model>
"""

        # Fallen logs
        for k, (lx, ly, lz, lroll, lpitch, lyaw) in enumerate(self.fallen_logs):
            sdf += f"""
    <!-- Natural Obstacle: Fallen Timber Log {k+1} -->
    <model name="fallen_log_{k+1}">
      <static>true</static>
      <pose>{lx:.2f} {ly:.2f} {lz:.2f} {lroll:.2f} {lpitch:.2f} {lyaw:.2f}</pose>
      <link name="link">
        <collision name="col">
          <geometry><cylinder><radius>0.15</radius><length>2.4</length></cylinder></geometry>
        </collision>
        <visual name="vis">
          <geometry><cylinder><radius>0.15</radius><length>2.4</length></cylinder></geometry>
          <material><ambient>0.32 0.22 0.15 1.0</ambient><diffuse>0.38 0.26 0.18 1.0</diffuse></material>
        </visual>
      </link>
    </model>
"""

        sdf += """  </world>
</sdf>
"""
        return sdf
